# SEE: https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md013.md
MD013: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md024.md
MD024:
  siblings_only: true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md033.md
MD033: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md034.md
MD034: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md003.md
MD003: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md022.md
MD022: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/md037.md
MD037: false
