repos:
  - repo: https://github.com/NHSDigital/nhs-notify-shared-modules
    rev: 3.1.2
    hooks:
      - id: scan-secrets
        args: [check=staged-changes]
      - id: check-file-format
        args: [check=staged-changes]
      - id: check-markdown-format
        args: [check=staged-changes]
      - id: check-english-usage
        args: [check=staged-changes]
